In [1]:
import numpy as np

# convert list into array

In [2]:
lst=list(range(1,25))
arr1=np.array(lst)

In [ ]:
print(type(arr1))
print(type(lst))


<class 'numpy.ndarray'>
<class 'list'>


# dirtect acces of array

In [4]:
arr1=np.array([1,2,23,3])# 
print(type(arr1))


<class 'numpy.ndarray'>


In [5]:
l=[1,2,4,5,52]
print(l)

[1, 2, 4, 5, 52]


In [6]:
arr1=np.arange(1,25) # arange is use in replace range function
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 2D array

In [7]:
arr1=np.array([[1,23],[12,33]])
arr1


array([[ 1, 23],
       [12, 33]])

## 3D array

In [8]:
arr1=np.array([[[1,23,3],[12,33,2],[1,23,4]],[[2,3,4],[1,23,44],[23,5,4]],[[12,3,34],[33,44,44],[3,4,4]]])
arr1
# print(type(arr1))


array([[[ 1, 23,  3],
        [12, 33,  2],
        [ 1, 23,  4]],

       [[ 2,  3,  4],
        [ 1, 23, 44],
        [23,  5,  4]],

       [[12,  3, 34],
        [33, 44, 44],
        [ 3,  4,  4]]])

In [9]:
arr1=np.zeros([1,22])
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [10]:
arr1=np.ones([1,5])
arr1

array([[1., 1., 1., 1., 1.]])

In [11]:
arr1=np.linspace(1,10,7)# it divide 1 to 10 in 7 parts
arr1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [12]:
arr1=np.linspace(1,10,7).reshape(7,1) # reshape is convert the array in a format or shape  
#here 7 is row and 1 is column
arr1

array([[ 1. ],
       [ 2.5],
       [ 4. ],
       [ 5.5],
       [ 7. ],
       [ 8.5],
       [10. ]])

In [13]:
arr1=np.arange(1,31).reshape(10,3)
arr1


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [14]:
arr1=np.arange(1,31).reshape(3,5,2)# here 3 is part 5 is row 2 column
arr1


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

# Random function

In [15]:
arr1=np.random.randint(10)
arr1

2

In [16]:
arr1=np.random.randint(1,5,10).reshape(5,2)#it give the random number in range 1 to 10
# here randint give the only integer value
arr1

array([[2, 3],
       [2, 1],
       [4, 2],
       [3, 2],
       [1, 4]])

# in 2d in random function

In [17]:
arr1=np.random.randint(1,5,10).reshape(5,2)
arr1


array([[1, 1],
       [1, 3],
       [3, 3],
       [4, 1],
       [3, 3]])

# in 3d

In [18]:
arr1=np.random.randint(1,5,16).reshape(2,4,2)
arr1


array([[[1, 4],
        [3, 2],
        [2, 1],
        [2, 1]],

       [[3, 2],
        [4, 1],
        [1, 1],
        [3, 1]]])

In [19]:
arr1=np.random.random(10)
arr1

array([0.5612552 , 0.95779047, 0.25048711, 0.58020622, 0.55664423,
       0.98196956, 0.80451002, 0.39340911, 0.24239312, 0.78657162])

In [20]:
arr1=np.arange(60).reshape(10,6)
arr1
arr1.dtype
arr1.ndim
arr1.size
arr1.shape

(10, 6)

In [21]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [22]:
arr1.flatten()# it convert the 2D or 3D into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [23]:
lst=np.array(list(range(1,33)))
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [24]:
lst.shape
# print(type(lst))

(32,)

In [25]:
lst=[[2,3,31],[1,23,3]]
arr1=np.array(lst)
arr1.shape
arr1

array([[ 2,  3, 31],
       [ 1, 23,  3]])

In [26]:
arr1.T.shape # transpose the 2d array
arr1.T # it is a method print transpose array 

array([[ 2,  1],
       [ 3, 23],
       [31,  3]])

In [1]:
import numpy as np

In [4]:
lst=[2,3,4,2,2,2,3,4]


arr=np.array(lst)

In [5]:
lst

[2, 3, 4, 2, 2, 2, 3, 4]

In [6]:
arr=np.array([1,23,44,5,55])
arr

array([ 1, 23, 44,  5, 55])

In [9]:
lst=list(range(1,23))

In [11]:
lst
len(lst)

22

# without range function create an array

In [12]:
arr=np.arange(1,19)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [13]:
arr=np.zeros((2,3))

In [14]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr=np.ones((10))

In [22]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
arr=np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
arr=np.random.randint(10)
arr

4

In [31]:
arr=np.random.randint(1,5,9)
arr

array([3, 1, 1, 4, 2, 3, 4, 4, 1])

# random function in 3d

In [32]:
arr=np.random.randint(1,5,(3,3))

In [34]:
arr=np.random.random(10)

arr

array([0.1181373 , 0.69130852, 0.06475119, 0.73981217, 0.8938198 ,
       0.08000057, 0.5565975 , 0.78785443, 0.37870921, 0.09287315])

In [39]:
arr.shape

(10,)

In [40]:
arr.dtype

dtype('float64')

In [37]:
arr.size

10

In [38]:
arr.ndim

1

In [42]:
arr.reshape(2,5)

array([[0.1181373 , 0.69130852, 0.06475119, 0.73981217, 0.8938198 ],
       [0.08000057, 0.5565975 , 0.78785443, 0.37870921, 0.09287315]])

In [45]:
arr.flatten()

array([0.1181373 , 0.69130852, 0.06475119, 0.73981217, 0.8938198 ,
       0.08000057, 0.5565975 , 0.78785443, 0.37870921, 0.09287315])

In [47]:
arr.ravel()

array([0.1181373 , 0.69130852, 0.06475119, 0.73981217, 0.8938198 ,
       0.08000057, 0.5565975 , 0.78785443, 0.37870921, 0.09287315])

# 2d list

In [48]:
list_2d=[[1,2,3],[22,3,34]]
list_2d

[[1, 2, 3], [22, 3, 34]]

In [49]:
arr=np.array(list_2d)

In [50]:
arr

array([[ 1,  2,  3],
       [22,  3, 34]])

In [51]:
arr.T

array([[ 1, 22],
       [ 2,  3],
       [ 3, 34]])

In [52]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
arr[2:5]

array([2, 3, 4])

In [55]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
eh